// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMKGNPZB1dBPbAjUDmKxbmzavH08dy1K0',
    appId: '1:401078638906:web:3e46648e9876e64dbb9803',
    messagingSenderId: '401078638906',
    projectId: 'apptienda-7fdec',
    authDomain: 'apptienda-7fdec.firebaseapp.com',
    databaseURL: 'https://apptienda-7fdec-default-rtdb.firebaseio.com',
    storageBucket: 'apptienda-7fdec.appspot.com',
    measurementId: 'G-78XXG151KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1JOADnrkWl88-5mDtDi0Sb00jvSC4nU0',
    appId: '1:401078638906:android:f8c7e2b98447cf91bb9803',
    messagingSenderId: '401078638906',
    projectId: 'apptienda-7fdec',
    databaseURL: 'https://apptienda-7fdec-default-rtdb.firebaseio.com',
    storageBucket: 'apptienda-7fdec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcn83Z5-WbVLbRbXYLWWggp-88tN4vmrc',
    appId: '1:401078638906:ios:babe7e702a5c915dbb9803',
    messagingSenderId: '401078638906',
    projectId: 'apptienda-7fdec',
    databaseURL: 'https://apptienda-7fdec-default-rtdb.firebaseio.com',
    storageBucket: 'apptienda-7fdec.appspot.com',
    iosBundleId: 'com.example.tiendaprincipal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcn83Z5-WbVLbRbXYLWWggp-88tN4vmrc',
    appId: '1:401078638906:ios:babe7e702a5c915dbb9803',
    messagingSenderId: '401078638906',
    projectId: 'apptienda-7fdec',
    databaseURL: 'https://apptienda-7fdec-default-rtdb.firebaseio.com',
    storageBucket: 'apptienda-7fdec.appspot.com',
    iosBundleId: 'com.example.tiendaprincipal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMKGNPZB1dBPbAjUDmKxbmzavH08dy1K0',
    appId: '1:401078638906:web:0646019feaf6bfffbb9803',
    messagingSenderId: '401078638906',
    projectId: 'apptienda-7fdec',
    authDomain: 'apptienda-7fdec.firebaseapp.com',
    databaseURL: 'https://apptienda-7fdec-default-rtdb.firebaseio.com',
    storageBucket: 'apptienda-7fdec.appspot.com',
    measurementId: 'G-2Q87DYL8BC',
  );
}
